@startuml casos_uso

left to right direction

actor "Usuário EVOA" as usuario

package "Módulo Vigilância" as vigilancia {
  usecase "V1: Fazer Denúncia de\nIrregularidade" as UC4
  usecase "V2: Registrar Evidência\nFotográfica" as UC5
  usecase "V3: Notificar Órgãos\nCompetentes" as UC6
  usecase "V4: Acompanhar Status das\nDenúncias" as UC7
}

usuario --> UC4: Executa
usuario --> UC7: Pode

UC5 .> UC6: Gera
UC4 .> UC5 : Inclui
