@startuml classes

!theme amiga

entity Usuario {
    + id : number
    + nome : string
}

entity Sistema {
    + id : number
    + nome : string
}

entity Desconto {
    + id : number
    + nome : string
}

@enduml